version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1338:5000"
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=db
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=zxc9047asdqq21
      - MYSQL_DATABASE=db_ctf
    # ports:
      # - "3307:3306"
    volumes:
      - ./query.sql:/docker-entrypoint-initdb.d/query.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    # ports:
      # - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3307
      - MYSQL_ROOT_PASSWORD=zxc9047asdqq21
